# DELPHINUS - ADVENTURE APP
# CS 467 - Winter 2017
# Team Members: Sara Hashem, Shawn Hillyer, Niza Volair

# gameplay_settings.py
# Description: Defines how much it costs to complete each of the actions in the game
# In general we can tweak this file to change the difficulty of the game and action economy
# Principal Author of this file per Project plan: Shawn Hillyer

# CITATIONS
# CITE:

STARTING_TIME = 5000

# Time costs
BUY_COST = -25
DROP_COST = -5
GO_COST = -100
HACK_COST = -50
INVENTORY_COST = 0
JAIL_COST = -500
LOOK_AT_COST = 0
LOOK_COST = 0
SPRAYPAINT_COST = -30
SKATE_COST = -30
STEAL_COST = -40
TAKE_COST = -10
TALK_COST = -15
USE_COST = -25
DOOR_COST = 5

# Speed boosts from various activites
HACK_LIGHT_SPEED_CHANGE = 4
SKATEBOARD_SPEED_INCREASE = 2
SNACK_SPEED_INCREASE = 1
SURGE_SPEED_INCREASE = 2
FLOPPY_DISK_SPEED_INCREASE = 3
RAM_SPEED_INCREASE = 5
BUG_SPEED_LOSS = -5
CAT_VIDEO_SPEED_COST = -2
HACK_LAUNCH_CODE_COST = -3
FIREBALL_ON_BINARY_SPEED_COST = -1
FIREALARM_SPEED_INCREASE = 3
FIREALARM_SPEED_DECREASE = 1
SKATE_LEDGE_SPEED_LOSS = -6

# Money costs
SUBWAY_GO_DOLLAR_COST = 5
CORRUPTED_FILE_CASH_PERCENT_LOSS = .25
CAT_VIDEO_CASH_PERCENT_LOSS = .50

# Coolness gain/loss
SPRAYPAINT_COOLNESS_INCREASE = 1
TRASH_CAN_SEARCH_COOLNESS_COST = -1
GRAPHICS_COOLNESS_INCREASE = 4
BUG_COOLNESS_LOSS = -1
FIREWALL_COOLNESS_COST = -1
BINARY_FILES_COOLNESS_COST = -1
BINARY_FILES_COOLNESS_INCREASE = 1
CAT_FAIL_COOLNESS_COST = -1
CAT_FAIL_COOLNESS_INCREASE = 1
CAT_FOOD_FAIL_COOLNESS_COST = -2
CAT_SUCCESS_COOLNESS_INCREASE = 5
FRESHMAN_SHAME = -1
CAT_SHAME = -3
PIGEON_SHAME = -2
CAT_APPROVAL = 5
SKATE_LEDGE_COOLNESS_INCREASE = 6